// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDoctor.DataAccess;

namespace SmartDoctor.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211106200107_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartDoctor.Models.Calificacion", b =>
                {
                    b.Property<int>("calificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("medicoId")
                        .HasColumnType("int");

                    b.Property<int>("pacienteId")
                        .HasColumnType("int");

                    b.Property<double>("puntuacion")
                        .HasColumnType("float");

                    b.HasKey("calificacionId");

                    b.HasIndex("medicoId");

                    b.HasIndex("pacienteId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("SmartDoctor.Models.Especialidad", b =>
                {
                    b.Property<int>("especialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("especialidadId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("SmartDoctor.Models.Estudio", b =>
                {
                    b.Property<int>("estudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("medicoId")
                        .HasColumnType("int");

                    b.HasKey("estudioId");

                    b.HasIndex("medicoId");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("SmartDoctor.Models.Experiencia", b =>
                {
                    b.Property<int>("experienciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("medicoId")
                        .HasColumnType("int");

                    b.HasKey("experienciaId");

                    b.HasIndex("medicoId");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("SmartDoctor.Models.Medico", b =>
                {
                    b.Property<int>("medicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("especialidadId")
                        .HasColumnType("int");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("residenciaId")
                        .HasColumnType("int");

                    b.Property<int>("sistemaOperativoId")
                        .HasColumnType("int");

                    b.HasKey("medicoId");

                    b.HasIndex("especialidadId");

                    b.HasIndex("residenciaId");

                    b.HasIndex("sistemaOperativoId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("SmartDoctor.Models.Paciente", b =>
                {
                    b.Property<int>("pacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("distrito_colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("parentescoId")
                        .HasColumnType("int");

                    b.Property<bool>("sexo")
                        .HasColumnType("bit");

                    b.HasKey("pacienteId");

                    b.HasIndex("parentescoId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SmartDoctor.Models.Parentesco", b =>
                {
                    b.Property<int>("parentescoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("parentescoId");

                    b.ToTable("Parentescos");
                });

            modelBuilder.Entity("SmartDoctor.Models.Residencia", b =>
                {
                    b.Property<int>("residenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("residenciaId");

                    b.ToTable("Residencias");
                });

            modelBuilder.Entity("SmartDoctor.Models.SistemaOperativo", b =>
                {
                    b.Property<int>("sistemaOperativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sistemaOperativoId");

                    b.ToTable("SistemaOperativos");
                });

            modelBuilder.Entity("SmartDoctor.Models.Calificacion", b =>
                {
                    b.HasOne("SmartDoctor.Models.Medico", "Medico")
                        .WithMany("Calificaciones")
                        .HasForeignKey("medicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDoctor.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("pacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SmartDoctor.Models.Estudio", b =>
                {
                    b.HasOne("SmartDoctor.Models.Medico", "Medico")
                        .WithMany("Estudios")
                        .HasForeignKey("medicoId");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SmartDoctor.Models.Experiencia", b =>
                {
                    b.HasOne("SmartDoctor.Models.Medico", "Medico")
                        .WithMany("Experiencias")
                        .HasForeignKey("medicoId");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SmartDoctor.Models.Medico", b =>
                {
                    b.HasOne("SmartDoctor.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("especialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDoctor.Models.Residencia", "Residencia")
                        .WithMany()
                        .HasForeignKey("residenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDoctor.Models.SistemaOperativo", "SistemaOperativo")
                        .WithMany()
                        .HasForeignKey("sistemaOperativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Residencia");

                    b.Navigation("SistemaOperativo");
                });

            modelBuilder.Entity("SmartDoctor.Models.Paciente", b =>
                {
                    b.HasOne("SmartDoctor.Models.Parentesco", "Parentesco")
                        .WithMany()
                        .HasForeignKey("parentescoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parentesco");
                });

            modelBuilder.Entity("SmartDoctor.Models.Medico", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("Estudios");

                    b.Navigation("Experiencias");
                });
#pragma warning restore 612, 618
        }
    }
}
